### ISSUE TITLE
Add travis ci integration!

### ISSUE THREAD

**Issue by Atsman** [igrishaev/etaoin#158]
It would be nice to have travis ci, for that we will see that prs are ok.

**Comment by igrishaev** [comment]
Agree.

**Comment by Atsman** [comment]
The easiest way will be to run at least for one browser like chrome

**Comment by marco-m** [comment]
Would be OK for you to use https://circleci.com instead than travis ? It supports building PRs too. The reason is that it would be the occasion for me to learn circleci and compare it with travis (that I already know). If you are OK at least trying it out, I can make a PR. What will be problematic is the graphical display. It looks like that circleci supports Selenium so it seems to support VNC and other virtual framebuffers. I was thinking of adding an env variable, something like ETAOIN_TEST_DRIVERS that, if present, will be used to initialize the list of drivers used by the test fixture.

**Comment by Atsman** [comment]
In my opinion, Travis is the de facto standard for open source projects and there is almost no difference from the user perspective. And Travis has much more documentation and so on compared to the circle. But you, of course, can do whatever you want. 

I was thinking about creating a docker image with everything that needed to run unit tests inside. With all browsers/drivers. And then run scripts using that docker image. And in that case, it is really doesn't matter what to use for the run.

**Comment by marco-m** [comment]
I did a PR for CircleCI. I think documentation for CircleCI is very good actually, I had no problems to bring Etaoin on Circle, and I never used it. CircleCI is also nice because it allows parallelism with what they call "workflows".

**Comment by igrishaev** [comment]
Thank you, let me take a look
