### ISSUE TITLE
Can etaoin support to print web page to PDF like Chrome or Firefox supported?

### ISSUE THREAD

**Issue by stardiviner** [igrishaev/etaoin#174]
RT. I found etaoin support screenshot api, I think print to PDF should be available too.

**Comment by igrishaev** [comment]
Hey @stardiviner , PDF printing is not fully supported in Webdriver protocol. All we can do is to run Chrome with additional parameters that create a pdf once the page has been loaded. It means you cannot create a pdf just in the middle of a session.

**Comment by igrishaev** [comment]
I can create a function that takes a URL and file path and then saves that URL into PDF. This PDF will represent the initial state of a page.

**Comment by igrishaev** [comment]
https://stackoverflow.com/questions/31136581/automate-print-save-web-page-as-pdf-in-chrome-python-2-7

**Comment by igrishaev** [comment]
After some investigations, I found you can do that just launching Chrome from a command line. Here is the way to do that: https://developers.google.com/web/updates/2017/04/headless-chrome#create_a_pdf_dom

But since the requested functionality is not a part of Webdriver protocol, I have to close it. There is nothing we can do at the moment to print pages to PDF on demand.

**Comment by stardiviner** [comment]
I see, thanks @igrishaev
