### ISSUE TITLE
Can't find log files

### ISSUE THREAD

**Issue by rutchkiwi** [igrishaev/etaoin#323]
Hi, thanks for this awesome library!

I'm having some trouble with starting firefox in my prod linux environent (I get invalid argument: can't kill an exited process) and I can't seem to produce any logs? I am starting it like so:

```
(e/firefox {:log-stdout "ffout.log" :log-stderr "fferr.log" :driver-log-level "trace"
                 :path-driver  "/app/vendor//geckodriver"
                 :path-browser "/app/vendor/firefox/firefox"})
```

but I can't seem to find any logs created anywhere. They should be generated in the same directory as I'm running clojure from right?

Am I enabling logging in an incorrect manner or is this a bug?

Thankful for any help!

**Comment by igrishaev** [comment]
Hi @rutchkiwi! For now, I don't see any issue with your code. Just some notes:

- since the `ffout.log` path is not absolute, the file will be written relative to the directory where the Clojure project was launched from. If you manage your app on the server with some linux stuff (init.d, systemct, etc)  I suggest you setting up an absolute path.

- second, the path `"/app/vendor//geckodriver"` looks a bit strange with the double slash, that might be a reason of the trouble.

Also, if you ssh to you server and run `geckodriver`, what happens then? Does the Webdriber HTTP server get started?

**Comment by rutchkiwi** [comment]
Thanks a lot for the help @igrishaev ! I will try to fix the // not sure why it's like that.

I did manage to find the log files now, as you said they were in the same directory so I have no idea what I did wrong before. So sorry for wasting you time! Should have slept on this instead 🤦‍♂️

**Comment by igrishaev** [comment]
No worries Victor, feel free to post your updates here when you have any.
