### ISSUE TITLE
How to log the found element in the browser console?

### ISSUE THREAD

**Issue by qleguennec** [igrishaev/etaoin#376]
When I query an element with etaoin, I get that kind of return: 0.6477551855860713-16 

What does it mean exactly and how can I exploit it? I'd like the log the found element in the browser console.

**Comment by qleguennec** [comment]
That's what I was missing from the readme, thank you.

Any way I could use these functions to execute a script with the HTML element in it in chrome, though? The w3c reference isn't very clear about it.

Something like:
```
console.log(arguments[0]) // arguments[0] is 0.6477551855860713-16
```
Which would log in the console:
`<span>Hello world</span>`

**Comment by Uunnamed** [comment]
Etaoin doesn't have direct access to the browser's console, but you can try to use the `js-execute` method to sending arbitrary js code, for example `(js-execute driver (format "console.log(%s)" (get-element-inner-html-el driver el)))`. But this may not work because of the possible presence of special characters in the received html.

**Comment by qleguennec** [comment]
Thank you for your answers, I found exactly what I was looking for (from the docs 😇)

`(js-execute @driver "console.log(arguments[0])" (el->ref el-ref))`
