### ISSUE TITLE
Method Names!

### ISSUE THREAD

**Issue by komcrad** [igrishaev/etaoin#54]
In Clojure you usually use '!' at the end of impure function names that change the state of an object. In this case, many of the functions change the state of a driver. Eg. (go! driver url) instead of (go driver url)
Your project is very similar to something I've been working on. May switch to this after further research. But I thought I'd mention the naming thing regarding driver mutating functions.

You are probably much more experienced in Clojure than me so correct me if I'm wrong.

**Comment by AdamFrey** [comment]
I would avoid the `!` in the function name. Most of the time in clojure code found in the wild a function that ends in `!`, isn't just a function that causes a side-effect, but rather more specifically it is a function that mutates the parameter that is passed to it. That's why `(swap! some-atom inc)` gets a `!`, but `(prn "side effect")` has no `!`. 

When you call `(go driver url)`, `driver` is a clojure atom that holds an immutable map that looks something like:
```
{:type :firefox
 :host "127.0.0.1"
 :port 8585
 :driver <driver process object>
 ...}
```

Calling `go!` does technically cause a side-effect to happen on your machine, but it doesn't mutate the driver atom at all, so I don't think renaming to `go!` would actually be idiomatic.

**Comment by komcrad** [comment]
Ahh. But if the driver variable was the actual driver process object, then the ! would make sense to use?

**Comment by AdamFrey** [comment]
that would be more of a tossup, I guess, but it would depend on the hypothetical implementation.

I maybe shouldn't have even included the `<driver process object>` in my example up top because it's actually a red herring. If you look at the source code, the driver process is set at the beginning, but it is only used in [one place](https://github.com/igrishaev/etaoin/blob/master/src/etaoin/api.clj#L2205), when you call `stop-driver`. Every other normal call like `go` ends up in [this function](https://github.com/igrishaev/etaoin/blob/master/src/etaoin/client.clj#L64) where you can see that no clojure vars or jvm objects are mutated at all. Instead an HTTP request is made to the external process listening on some port. That's different than most idiomatic `!` functions which indicate that some object within your clojure program is being mutated.

**Comment by igrishaev** [comment]
Hi @komcrad,

sorry for the delayed answer. Definitely you are right about adding ! at the end of methods that change some state. But this is done rather to stress our decisions and highlight them in our code. But when dealing with a browser, avery single action made on it changes its state. So there is no sense to rename each function. Just consider every api call as something that changes the state.

**Comment by igrishaev** [comment]
btw thanks @AdamFrey for your notes on the topic.

**Comment by komcrad** [comment]
I also thought this was the reason. The change in state is so obvious that the ! would probably be redundant. I appreciate all the thoughts on it.
