### ISSUE TITLE
Add Edge/IE support

### ISSUE THREAD

**Issue by igrishaev** [igrishaev/etaoin#83]

**Comment by frenata** [comment]
Some considerations as I work on this:

* The IE 6-11 webdriver *might* be runnable via `wine` (I'll need to check/verify this), but the Edge driver is distinctly not, it will have to be run via a VM. Helpful error messages to this effect would be useful.

* Most of the work will be in `driver.clj`, but I expect I'll run into eccentricities of implementation that will need to be worked around with more multimethod definitions in `api.clj`

[Edge WebDriver documentation](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/tools/webdriver)
[IE WebDriver documentation](https://msdn.microsoft.com/en-us/library/dn800898(v=vs.85).aspx)

**Comment by igrishaev** [comment]
Thank you. My suggestions would be:
- at the moment, add Edge only. It's pretty developed and has webdriver support. But I don't have a clue about IE.
- Development might be done with Virtual box using the official [Microsoft images](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
). They live for 90 days that would be enough.
- For the most of multimethods in the code, add `:edge` key and test whether the method really works as expected.
- If some methods require to implement JsonWire Protocol, let's discuss it.
- If you start a new branch, please share it with me.

**Comment by frenata** [comment]
Yeah Edge / VirtualBox is where I'm starting for sure. I'll be working on it some this week: at the moment I have a development environment setup on VirtualBox and some really basic steps toward getting Edge working.

https://github.com/frenata/etaoin/tree/edge-support is my WIP branch.

**Comment by anthonygalea** [comment]
@frenata did you by any chance make further progress on this?

I briefly looked into it and after setting up a VM I found out that Edge now runs native on MacOS. Progress so far here: https://github.com/anthonygalea/etaoin/tree/edge

**Comment by frenata** [comment]
Sadly I wasn't able to spend time on this, but I'm interested to see what you've worked on. :)

**Comment by anthonygalea** [comment]
Thanks for the info @frenata.

Had tested only on MacOS so far but I just cloned the [edge branch](https://github.com/anthonygalea/etaoin/tree/edge) into a virtual machine running one of the [microsoft images](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and installed edge following [these instructions](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#installation). Tests ran successfully except for failures fixed in [this pull request](https://github.com/igrishaev/etaoin/pull/217).

Just to be clear this is not the original EdgeHTML but the new version of [Edge based on Chromium](https://en.wikipedia.org/wiki/Microsoft_Edge#Discontinuation_of_EdgeHTML_and_adoption_of_Chromium_(2019–present)).

**Comment by igrishaev** [comment]
Ok, for now, let's start with Edge as it would be easier.

**Comment by igrishaev** [comment]
- Add `:edge` browser type;
- add related macros and functions, e.g. with-edge, when-not-edge, etc
- add tests
