### ISSUE TITLE
Screenshots are not taken when postmortem is put in fixture

### ISSUE THREAD

**Issue by ingesolvoll** [igrishaev/etaoin#93]
With the following setup, screenshots do not appear in my target folder:

```
(use-fixtures :each
              (fn [test-fn]
                    (et/with-chrome-headless
                      {:size [1500 1000]} driver
                     (binding [*driver* driver]
                        (et/with-postmortem
                         *driver*
                         {:dir "./target"}
                        (test-fn))))))
```

However, if I put the postmortem wrapper directly within `deftest`, it works.

Am I doing something wrong, or is this a bug? I've been trying to figure out what the difference is, if there's something with how the `try` macro works...

**Comment by igrishaev** [comment]
@ingesolvoll this is a know issue that is caused by `clojure.test` framework. It consumes all the exceptions inside a test, do the fixture does not see any exception occurred. Check the latest readme.md, yesterday I put a note about that.

There might be two options there:
1. wrap not a test with a fixture, but the test's body with `with-postmortem` handler. 
that would definitely work;
2. check that pull-request: https://github.com/igrishaev/etaoin/pull/56/files Inside, there is way to deal with that.

**Comment by igrishaev** [comment]
As a result, I'm going to either to grab the solution posted in that PR, or provide a special macro to wrap test's body. The issues is #94

**Comment by ingesolvoll** [comment]
Ok, so my assumptions were right then :) Thanks!

The screenshot feature is definitely something I want for all the tests without adding the boilerplate of stating it for each test. So the solution in the PR sounds good.

So far, my experience with etaoin has been flawless and a lot of fun, great work!

**Comment by igrishaev** [comment]
fixed, see readme
